FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-devel-ubi9

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_NO_BUILD_ISOLATION=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE="copy" \
    UV_TORCH_BACKEND="cu128" \
    UV_CACHE_DIR="/opt/uv/cache" \
    UV_PYTHON_BIN_DIR="/opt/uv/bin" \
    UV_PYTHON_INSTALL_DIR="/opt/uv/python" \
    UV_PYTHON_CACHE_DIR="/opt/uv/cache/python" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    MPLBACKEND=Agg \
    PATH="/opt/python3/bin:$PATH"

RUN uv venv /opt/python3 --python 3.11

RUN --mount=type=cache,target=/opt/uv/cache \
    uv pip install ninja pip "setuptools<82" wheel

RUN --mount=type=cache,target=/opt/uv/cache \
    uv pip install \
    numpy==2.0.2 \
    scipy==1.13.1 \
    mne==1.8.0 \
    matplotlib==3.9.4 \
    eeglabio==0.1.3

RUN --mount=type=cache,target=/opt/uv/cache \
    uv pip install torch==2.8.0 --index-url https://download.pytorch.org/whl/${UV_TORCH_BACKEND}

WORKDIR /app

CMD ["/bin/bash"]
