FROM debian:13-slim

LABEL maintainer="lapluis"

ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive

ARG ARGYLL_VERSION=3.5.0
ARG ARGYLL_URL=https://www.argyllcms.com/Argyll_V${ARGYLL_VERSION}_linux_x86_64_bin.tgz

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends ca-certificates && \
    cp /etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources.bak && \
    cat <<EOF > /etc/apt/sources.list.d/debian.sources
Types: deb
URIs: https://mirrors.tuna.tsinghua.edu.cn/debian
Suites: trixie trixie-updates trixie-backports
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg

Types: deb
URIs: https://security.debian.org/debian-security
Suites: trixie-security
Components: main contrib non-free non-free-firmware
Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
EOF

RUN \
    apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends curl tar libx11-6 libxau6 libxdmcp6 libxext6 libxinerama1 libxrandr2 libxss1 libxxf86vm1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN \
    mkdir -p /opt/argyll && \
    curl -fL "${ARGYLL_URL}" -o /tmp/argyll.tgz && \
    tar -xzf /tmp/argyll.tgz -C /opt/argyll --strip-components=1 && \
    rm /tmp/argyll.tgz && \
    rm -rf /opt/argyll/doc /opt/argyll/usb

ENV PATH="/opt/argyll/bin:${PATH}"

CMD ["bash"]
